import pptxgen from "pptxgenjs";

interface PptSlide {
    title: string;
    points: string[];
}

interface PptData {
    title: string;
    subtitle?: string;
    slides: PptSlide[];
    // legacy/alternate key kept for backwards compat
    sections?: { heading: string; points: string[] }[];
}

const normalizeData = (data: PptData): { title: string; subtitle: string; slides: PptSlide[] } => {
    const rawSlides = Array.isArray(data.slides)
        ? data.slides.map((s) => ({
              title: typeof (s as any)?.title === "string" ? (s as any).title : String((s as any)?.title ?? "Untitled"),
              points: Array.isArray((s as any)?.points)
                  ? (s as any).points.filter((p: unknown) => typeof p === "string")
                  : [],
          }))
        : Array.isArray(data.sections)
          ? data.sections
                .filter((s) => s && typeof s.heading === "string" && Array.isArray(s.points))
                .map((s) => ({
                    title: s.heading,
                    points: s.points.filter((p) => typeof p === "string"),
                }))
          : [];

    return {
        title: String(data.title ?? "Relay Presentation"),
        subtitle: typeof data.subtitle === "string" ? data.subtitle : "",
        slides: rawSlides.filter((s) => s.title || s.points.length > 0),
    };
};

const generatePpt = async (data: PptData): Promise<Buffer> => {
    const normalized = normalizeData(data);

    const pptx = new pptxgen();
    pptx.author = "Relay";
    pptx.company = "Relay";
    pptx.title = normalized.title;
    pptx.subject = normalized.subtitle;

    // Cover slide
    const cover = pptx.addSlide();
    cover.background = { color: "111827" };
    cover.addText(normalized.title, {
        x: 0.5,
        y: 1.6,
        w: 9,
        h: 1.4,
        fontSize: 38,
        bold: true,
        color: "FFFFFF",
        align: "center",
    });
    if (normalized.subtitle) {
        cover.addText(normalized.subtitle, {
            x: 0.5,
            y: 3.2,
            w: 9,
            h: 0.8,
            fontSize: 18,
            color: "9CA3AF",
            align: "center",
        });
    }
    cover.addText("Generated by Relay", {
        x: 0.5,
        y: 4.8,
        w: 9,
        h: 0.4,
        fontSize: 11,
        color: "6B7280",
        align: "center",
    });

    // Content slides
    let slideNumber = 2; // cover is slide 1
    for (const slideData of normalized.slides) {
        const slide = pptx.addSlide();
        slide.background = { color: "FFFFFF" };
        slide.addText(slideData.title, {
            x: 0.5,
            y: 0.3,
            w: 9,
            h: 0.9,
            fontSize: 28,
            bold: true,
            color: "111827",
        });
        slide.addShape("line", {
            x: 0.5,
            y: 1.25,
            w: 9,
            h: 0,
            line: { color: "E5E7EB", width: 1.5 },
        });

        let y = 1.6;
        const points = slideData.points.slice(0, 8);
        if (points.length === 0) {
            slide.addText("(No points provided)", {
                x: 0.7,
                y,
                w: 8.6,
                h: 0.5,
                fontSize: 15,
                italic: true,
                color: "9CA3AF",
            });
        }
        for (const point of points) {
            slide.addText(String(point), {
                x: 0.7,
                y,
                w: 8.6,
                h: 0.7,
                fontSize: 15,
                color: "374151",
                bullet: { code: "2022", indent: 14 },
            });
            y += 0.75;
        }

        slide.addText(`${slideNumber}`, {
            x: 9.2,
            y: 5.1,
            w: 0.6,
            h: 0.3,
            fontSize: 10,
            color: "9CA3AF",
            align: "right",
        });
        slideNumber += 1;
    }

    const output = await pptx.write({ outputType: "nodebuffer" });
    return Buffer.isBuffer(output) ? output : Buffer.from(output as Uint8Array);
};

export { generatePpt };
export type { PptData, PptSlide };
